### ISSUE TITLE
Can't make Pt3Player-MSX2-Demo example work

### ISSUE THREAD

**Issue by SaffronCR** [ericb59/Fusion-C-v1.2#2]
Hi,

First of all thank you so much for this wonderful library! kudos on the hard work.

I've been using it for writing a small RPG, and so far things work great. At least until I tried to play some music.

I've tried to compile the Pt3Player-MSX2-Demo example, but the music never plays. I've tried with a lot of other different examples and they work as expected, I'm also using the library with my game and it's working. So I was wondering if maybe the code of this example is old or different from the actual executable file? I've tried with the .com file that is already generated and that one works as expected.

Thanks!

**Comment by ericb59** [comment]
Hello,
Thank you for using FUSION-C :-)
I've checked your Dungeon Crawler and I like it very much !

About the Pt3Player-MSX2-Demo source code. I've tested it and it play normally on my MSX2 8250 testing machine (OPenMSX). Which MSX2 model did you try ?

It is weird you can use the .com with no problem ?!!!

**Comment by SaffronCR** [comment]
I'm using Philips_NMS_8255 configuration in openmsx (I've tried with others and also in a real MSX2 VG-8235). it runs the program but this is what that appears in screen: [https://ibb.co/4gdNmtf](https://ibb.co/4gdNmtf)

I'm compiling and running the Pt3Player-MSX2-Demo.c file using compil.bat

Maybe that batch file is missing something?

This is the output when I compile the example:

```
C:\Develop\MSX\Fusion-C-v1.2-master\Working Folder>compil Pt3Player-MSX2-Demo
-------- Compilation of :
Pt3Player-MSX2-Demo
.
used unbound variable in replacement
... Compilation OK

C:\Develop\MSX\Fusion-C-v1.2-master\Working Folder>hex2bin -e com Pt3Player-MSX2-Demo.ihx
hex2bin v1.0.12, Copyright (C) 2012 Jacques Pelletier & contributors

Lowest address  = 00000100
Highest address = 00004886
Pad Byte        = FF
8-bit Checksum = A0
        1 archivo(s) copiado(s).
Done.
```

**Comment by ericb59** [comment]
Hello,
Sorry I forgot to reply to this message.
Do you use SDCC 3.6? I recommend version 3.6 for now, even if it is already old.
This error that you describe seems to come from SDCC 3.7 in any case.
