### ISSUE TITLE
Error in the documentation

### ISSUE THREAD

**Issue by bengalack** [ericb59/Fusion-C-v1.2#3]
Hi. Thanks for such a fantastic package! Helps me A LOT. Keep it up.

Just wanted to point out that the docs says this:

Palette
typedef struct {
unsigned char color ; // color number 0..15
unsigned char R ; // 0..7 red brightness
unsigned char G ; // 0..7 green brightness
unsigned char B ; // 0..7 blue brightness
} ColRGB ;

and the source code says this:

/* Palette */
typedef struct {
	unsigned char colour;	// colour number 0..15
	unsigned char R;		// 0..7	red brightness
	unsigned char G;		// 0..7	green brightness
	unsigned char B;		// 0..7	blue brightness
} ColRGB;

I get compilation errors on "color" :)

**Comment by ericb59** [comment]
thank you very much for notifying this.
I will make the correction on the 2 problems you pointed.
