### ISSUE TITLE
Exit(char N) does not exit

### ISSUE THREAD

**Issue by bengalack** [ericb59/Fusion-C-v1.2#4]
Hi. Thanks for such a fantastic package, once again.

I can't get the function Exit(char N) to exit, the program just returns to program and continues.

Also, the documentation (pdf) says that the call is "void exit(char N)" - with a lowercase e, while in the code/headerfile uppercase is used.

Just wanted to let you know, so things could be updated in a future release.

**Comment by ericb59** [comment]
thank you very much for notifying this.
I will make the correction on the 2 problems you pointed.
