### ISSUE TITLE
IntBios and IntDos (IntDosBios.s) boot the computer in ROM projects.

### ISSUE THREAD

**Issue by DamnedAngel** [ericb59/Fusion-C-v1.2#5]
IntBios and IntDos (IntDosBios.s), as well as dependent routines (like ReadMSXtype) don't work in ROM projects. They rely self-modifying code (they (try to) change ibcladr) and, being unable to set the proper routine address, they end up jumping to 0x0000 and booting the computer.

**Comment by ericb59** [comment]
Hello,
IntBios, IntDos, ReadMSXType, and others functions that are using interslot call cannot be used in a ROM Project. They are made to work from MSX-DOS only.
If you wish to use FUSION-C To produce ROM file, it's possible, but you must avoid all functions that are using a direct BIOS Call.

Anyway. By using new version of SDCC (4.0), using the IntBIOS/INTDOS method do not works anymore. So I 've written new functions for the upcoming Fusion-c 1.3. But they are still useless for ROM projects.
