### ISSUE TITLE
Bug in hmmm x coordinate

### ISSUE THREAD

**Issue by Ray-Hoo** [ericb59/Fusion-C-v1.2#8]
When I copy a part of the screen with the hmmm command and put in on a certain target location the location is off by 1 pixel. When I move it to the right with 1 pixel, it moves with 2 pixels. So it looks like there is a bug in the X coordinate.

**Comment by ericb59** [comment]
Hello,

What is the screen mode you are using ?

**Comment by ericb59** [comment]
If you are using Screen mode 5 or 7 , this is normal. It's a hardware limitation.

**Comment by Ray-Hoo** [comment]
Yes, I am using screen 5. Could you please explain a bit more about this hardware limitation? As I did not experience this when using Turbo Pascal on the MSX (or I have not noticed it).

**Comment by ericb59** [comment]
Hi,

You can check in the V9938 manual : http://map.grauw.nl/resources/video/yamaha_v9938.pdf
Page 62
That in G4 and G6 mode (Screen mode 5 and 7) the lower bit of SX and DX are lost.
So coordinates must be even numbers.

**Comment by ericb59** [comment]
Hi,

If you have a GitHub account and want to be included in the Beta test of
Fusion-C 1.3, let me know your GitHub Account.

See you
Eric
